# Generated by Django 4.2.11 on 2026-06-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile_consultation_fee_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waiting', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('treated', 'Treated'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='registered', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Patient's reported symptoms"),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='staff.staffprofile'),
        ),
    ]
