# Generated by Django 4.2.11 on 2026-06-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile_consultation_fee_and_more'),
        ('patients', '0002_patient_assigned_doctor_patient_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lab_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_patients', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_test_requested',
            field=models.TextField(blank=True, help_text='Tests requested by doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_test_results',
            field=models.TextField(blank=True, help_text='Results from laboratory'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waiting', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('lab_requested', 'Lab Test Requested'), ('lab_in_progress', 'Lab Test In Progress'), ('lab_completed', 'Lab Results Ready'), ('treated', 'Treated'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='registered', max_length=20),
        ),
    ]
