# Generated by Django 4.2.11 on 2026-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_lab_technician_patient_lab_test_requested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='middle_name',
            new_name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lab_technician',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID / Aadhar / Passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lab_test_requested',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lab_test_results',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
