# Generated by Django 4.2.11 on 2026-07-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_middle_name_patient_insurance_provider_and_more'),
        ('billing', '0002_bill_claim_status_bill_insurance_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='claim_status',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='insurance_claim_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_mrn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('insurance', 'Insurance Claimed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
