# Generated by Django 4.2.11 on 2026-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
