# Generated by Django 4.2.11 on 2026-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_options_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='max_patients_per_day',
            field=models.IntegerField(default=20),
        ),
    ]
