# Generated by Django 4.2.11 on 2026-07-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_middle_name_patient_insurance_provider_and_more'),
        ('staff', '0004_alter_staffprofile_options_and_more'),
        ('pharmacy', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_prescriptions', to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity_prescribed',
            field=models.IntegerField(default=1),
        ),
    ]
